import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Aggregateur d'offres d'emploi en Centrafrique",
  description: "Une plateforme centralisée pour trouver des offres d'emploi en Centrafrique, spécialement conçue pour les ONG et les entreprises locales.",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 05a17f74438f4e8962ad149d51a2c9e672ed52e3
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
<<<<<<< HEAD
      lang="fr"
=======
      lang="en"
>>>>>>> 05a17f74438f4e8962ad149d51a2c9e672ed52e3
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
